version: "3.8"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'e_comm_app:v1'
    container_name: app
    ports:
      - 8000:8000
    restart: always
    # depends_on:
    #   - db

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$(DB_USER)
      - POSTGRES_PASSWORD=$(DB_PASSWORD)
      - POSTGRES_BD=$(DB_NAME)

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - 5050:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=$(PGADMIN_EMAIL)
  #     - PGADMIN_DEFAULT_PASSWORD=$(PGADMIN_PASSWORD)
  #     - POSTGRES_BD=$(DB_NAME)
  #   depends_on:
  #     - db
