version: "3.8"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'e_comm_app:v2'
    container_name: app
    # command: bash -c "alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    restart: always
    volumes:
    # I added mounts individually to avoid messing with the .venv in the containier
      - ./e_commerce_app:/opt/e_commerce_app
      - ./alembic:/opt/alembic
      - ./env:/opt/env
    depends_on:
      - db

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - env/example.env

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    depends_on:
      - db
